### ISSUE TITLE
Build report parser can't handle line breaks for Module INF Paths

### ISSUE THREAD

**Issue by zurcher** [tianocore/edk2-pytool-library#157]
The Build Report will line break after 120 characters which causes parser errors when Module INF Paths are longer than 101 characters.

**Comment by Javagedes** [comment]
When a _Module INF Path_ wraps to a new line within a **Module Summary** section, the parser cuts off the INF path at the new line, resulting in an incorrect parsed value for the INF path. Due to this, ```FindComponentByInfPath()``` fails and the fully parsed module will be missing the FV that it is a part of. This results in a non-halting error but does mean that the data the parser is providing is incorrect.
