### ISSUE TITLE
A duplicate name in a workspace will result in GetEdk2RelativePathFromAbsolutePath returning a bad result

### ISSUE THREAD

**Issue by apop5** [tianocore/edk2-pytool-library#168]
Admittedly, this is a case of poorly named folders resulting in this failure case.  But given the information that the Edk2Path Class has available, it should be able to resolve this correctly. 

            PlatformClientPkg/           <-- workspace root
                CLIENT_PKG/       <-- packages path
                    ClientPkg/   <-- A edk2 package
                        ClientPkg.DEC
                        module1/
                            module1.INF
                        module2/
                            module2.INF
                            x64/
                               TestFile.c

Calling GetAbsolutePathOnThisSystemFromEdk2RelativePath( "ClientPkg/ClientPkg.DEC") returns the correct result. 
Calling GetEdk2RelativePathFromAbsolutePath with the return of the above call ends up returning an invalid path
"ClientPkg/CLIENT_PKG/ClientPkg/ClientPkg.dec"

I wrote a test case, https://github.com/apop5/edk2-pytool-library/tree/poorpathutilityname, which will reproduce this as part of the path_utilities_test.py.

**Comment by Javagedes** [comment]
@apop5 Thanks, I will look into this! At first glance I think the issue is with the following line:

https://github.com/tianocore/edk2-pytool-library/blob/e91741433d1c84f1252ba9bce1d71ef4d158a640/edk2toollib/uefi/edk2/path_utilities.py#L100

the find method finds the first occurrence, which in the situation above is the workspace root instead of the edk2 package.

I'll double check and get a fix in. Thank you for writing a test case 👍

**Comment by Javagedes** [comment]
@apop5 #172 fixes the actual problem that this issue was created for, however I'm going to add your test case in #169 to ensure the situation is covered in the future.
