### ISSUE TITLE
[Bug]: Exception in locate_tools with specific environments

### ISSUE THREAD

**Issue by jorticus-msft** [tianocore/edk2-pytool-library#307]
### Contact Details

jasanson

### Describe the Bug

Building locally results in the following exception:
```
ERROR - Traceback (most recent call last):
  File "C:\Git\UEFI\venv\lib\site-packages\edk2toolext\environment\uefi_build.py", line 197, in Go
    ret = self.PostBuild()
  File "C:\Git\UEFI\venv\lib\site-packages\edk2toolext\environment\uefi_build.py", line 382, in PostBuild
    ret = self.PlatformPostBuild()
  File "C:\Git\UEFI\MyPlatformPkg\PlatformBuild.py", line 1131, in PlatformPostBuild
    ret = self.build_capsule()
  File "C:\Git\UEFI\MyPlatformPkg\PlatformBuild.py", line 1718, in build_capsule
    ret = self.Helper.PackageFmpImageAuth(...snip...)
  File "C:\Git\UEFI\MU_BASECORE\BaseTools\Plugin\Edk2ToolHelper\Edk2ToolHelper.py", line 98, in PackageFmpImageAuth
    SignToolPath = FindToolInWinSdk("signtool.exe")
  File "C:\Git\UEFI\venv\lib\site-packages\edk2toollib\windows\locate_tools.py", line 316, in FindToolInWinSdk
    results = QueryVcVariables(variables, product, arch)
  File "C:\Git\UEFI\venv\lib\site-packages\edk2toollib\windows\locate_tools.py", line 206, in QueryVcVariables
    raise Exception(stderr.decode("mbcs"))
Exception: The input line is too long.
The syntax of the command is incorrect.
```

This is due to QueryVcVariables appending to the console environment each time it is called, and eventually it fills up the environment such that `subprocess.Popen()` fails to execute with the above exception.

Most developers don't encounter this with the minimum VC++ installation requirements, but once you start installing other Visual Studio SDKs, the QueryVcVariables can become quite large.

I have worked around the issue by capturing the environment once at startup, then re-using that environment for each invocation of QueryVcVariables:
```diff
+environ = os.environ.copy()

def QueryVcVariables(...):
-    popen = subprocess.Popen('"%s" %s & set' % (vcvarsall_path, arch), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
+    popen = subprocess.Popen('"%s" %s & set' % (vcvarsall_path, arch), stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=environ)

```

### Reproduction steps

1. Install Visual Studio with C++ for both Desktop and Driver development, C# for UWP development, etc.
2. Build a UEFI project in a way that calls `FindToolInWinSdk`. For me that would be telling it to build and sign capsules.

### Expected behavior

Build should succeed

### What Python version are you using?

Python 3.10

### Execution Environment

Windows 11

**Comment by Javagedes** [comment]
@jorticus-msft I will look into this. Thank you!

**Comment by Javagedes** [comment]
@jorticus-msft I am not able to replicate the issue via your example. As shown in your example, you are using the Helper function self.Helper.PackageFmpImageAuth()`, which eventually calls `FindToolInWinSdk("signtool.exe")` which is where `QueryVCVariables()` is called. As you suggested, running `FindToolInWinSdk()` many times will eventually cause the error you linked.

As a test, I ran `FindToolInWinSdk("singtool.exe")`  1000 times in a loop and the number lines returned from vcvarsall.bat.
I verified the returned rows and total length of vcvarsall.bat remained unchanged and that os.environ entries and total length remained unchanged. Due to this, I believe environment pollution is coming from somewhere else (unless I am misunderstanding your issue).

Thanks!
Joey

**Comment by Javagedes** [comment]
Hello, yes on the edk2-pytool-extensions side (stuart commands), we manipulate the `os.environ` through our environment descriptor files and external dependencies; 40 paths seem a bit much and it may be necessary to evaluate scope usage to reduce the amount of in-scope, but unused, descriptors / external dependencies as each will edit the `os.environ` in some way. 

I should be able to catch the exception when the exception message is `The input line is too long.` and throw a better worded error about the PATH length. I'll work on that and tag you in the PR if I can get it working!

**Comment by Javagedes** [comment]
@jorticus-msft The reason the limit you mentioned does not line up perfectly is because this 8192 limitation is for all environment variables, not just the PATH. Therefore once the total length of all of the environment variables reach 8192, we throw the exception you mentioned above.

There is actually a second layer to this issue that I'm working through now. That is the fact that when an individual environment variable grows over 8191, that variable is ignored. Because of this, if the PATH grows over 8191, PATH is ignored. When this happens, we no longer throw the above error, but we fail to find the what we are looking for (depending on if it's found in the PATH variable). I'm working to handle warning for both.

**Comment by Javagedes** [comment]
PR to example on the logging message: #320
